#!/usr/bin/env bash
# build_editor.sh — ONE-TIME offline vendoring of CodeMirror 6 into a single
# self-contained ESM bundle committed at vendor/codemirror/codemirror.js.
#
# This is a build-TIME step (like build_assembler.sh for wat2wasm), NOT a
# playground serve-time build: the produced bundle is a committed static artifact
# the page loads directly via the import-map in index.html
# (`"codemirror": "./vendor/codemirror/codemirror.js"`).  The zero-build /
# statically-served property of the playground is preserved.
#
# Re-roll the bundle only when bumping CodeMirror versions.  Requires node (v24
# recommended) + network for `npm install` / `npx esbuild`.
#
# Pinned CM6 packages (installed at last roll):
#   @codemirror/state 6.7.0   @codemirror/view 6.43.5   @codemirror/language 6.12.4
#   @codemirror/commands 6.10.4   @codemirror/lint 6.9.7   @codemirror/search 6.7.1
#   @codemirror/autocomplete 6.20.3   @lezer/highlight 1.2.3
# Bundle: ~393 KB minified ESM.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/editor-build"
VENDOR_DIR="$SCRIPT_DIR/vendor/codemirror"

mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

# Facade re-exporting exactly the CM6 API surface the playground uses.
cat > cm6-entry.js <<'ENTRY'
export { EditorState, StateEffect, StateField, Compartment } from '@codemirror/state';
export {
  EditorView, keymap, lineNumbers, highlightActiveLine,
  highlightActiveLineGutter, drawSelection, rectangularSelection,
  crosshairCursor, highlightSpecialChars, tooltips,
} from '@codemirror/view';
export {
  StreamLanguage, LanguageSupport, HighlightStyle, syntaxHighlighting,
  bracketMatching, indentOnInput, foldGutter, foldKeymap, indentUnit, StringStream,
} from '@codemirror/language';
export { tags } from '@lezer/highlight';
export {
  defaultKeymap, history, historyKeymap, indentWithTab,
} from '@codemirror/commands';
export { setDiagnostics, lintGutter, forEachDiagnostic } from '@codemirror/lint';
export {
  closeBrackets, closeBracketsKeymap, autocompletion, completionKeymap,
} from '@codemirror/autocomplete';
export { searchKeymap, highlightSelectionMatches } from '@codemirror/search';
ENTRY

echo "==> npm install CodeMirror 6 packages"
npm install --no-audit --no-fund \
  @codemirror/state@6 @codemirror/view@6 @codemirror/language@6 \
  @codemirror/commands@6 @codemirror/lint@6 @codemirror/search@6 \
  @codemirror/autocomplete@6 @lezer/highlight@1

echo "==> esbuild → single minified ESM bundle"
npx --yes esbuild@0.25 cm6-entry.js --bundle --format=esm --minify \
  --outfile=cm6-bundle.js --log-level=warning \
  --banner:js='// CodeMirror 6 — vendored single-ESM bundle for the Medaka playground. Generated by playground/build_editor.sh (do not edit by hand).'

mkdir -p "$VENDOR_DIR"
cp cm6-bundle.js "$VENDOR_DIR/codemirror.js"

size=$(wc -c < "$VENDOR_DIR/codemirror.js" | tr -d ' ')
echo "==> Vendored $VENDOR_DIR/codemirror.js ($size bytes)"
echo "==> Done. (editor-build/node_modules is gitignored; the bundle is committed.)"
